In [1]:
import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
  print(os.path.join(dirname, filename))

In [2]:
train=pd.read_csv('/content/data (1).csv')
train.sample(20)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
7186,2008-09-08 00:00:00-04:00,13.022795,13.097282,12.737262,13.016587,63278600,0.00,0.0
7538,2010-02-01 00:00:00-05:00,12.606479,12.787774,12.587055,12.697127,50338300,0.00,0.0
9176,2016-08-03 00:00:00-04:00,27.629613,27.775459,27.540488,27.751152,18388800,0.26,0.0
633,1982-09-17 00:00:00-04:00,0.197472,0.197472,0.196020,0.196020,42432000,0.00,0.0
2063,1988-05-13 00:00:00-04:00,0.553211,0.561923,0.544499,0.555389,22377600,0.00,0.0
5290,2001-02-21 00:00:00-05:00,17.642546,18.638496,17.357988,17.500267,51582200,0.00,0.0
5828,2003-04-16 00:00:00-04:00,10.291652,10.497944,10.199967,10.406259,106294400,0.00,0.0
9969,2019-09-27 00:00:00-04:00,44.415860,44.933445,44.161452,44.547447,14845700,0.00,0.0
8736,2014-11-03 00:00:00-05:00,25.771054,26.281748,25.755809,26.152170,28703600,0.00,0.0
9576,2018-03-07 00:00:00-05:00,42.411700,43.518902,42.344083,43.375217,31801900,0.00,0.0
6442,2005-09-22 00:00:00-04:00,14.289544,14.441312,14.190311,14.336242,42372800,0.00,0.0
3511,1994-02-02 00:00:00-05:00,2.269937,2.304994,2.252408,2.287465,50043200,0.00,0.0
3259,1993-02-04 00:00:00-05:00,1.908102,1.929933,1.851339,1.908102,171360000,0.00,0.0
3754,1995-01-20 00:00:00-05:00,2.474260,2.483050,2.413283,2.419325,146233600,0.00,0.0
2405,1989-09-20 00:00:00-04:00,0.535787,0.548855,0.531431,0.544499,35619200,0.00,0.0
2468,1989-12-19 00:00:00-05:00,0.522719,0.544499,0.522719,0.540143,40672000,0.00,0.0
7161,2008-08-01 00:00:00-04:00,13.830115,13.891802,13.558694,13.786935,42123200,0.00,0.0
2852,1991-06-27 00:00:00-04:00,0.805859,0.810215,0.788435,0.794969,46534400,0.00,0.0
303,1981-05-29 00:00:00-04:00,0.239580,0.239580,0.238127,0.238127,27091200,0.00,0.0
3736,1994-12-23 00:00:00-05:00,2.219364,2.228154,2.206179,2.212772,23969600,0.00,0.0

In [3]:
train.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,11289.000000,11289.000000,11289.000000,11289.000000,1.128900e+04,11289.000000,11289.000000
mean,14.986168,15.185892,14.787731,14.985933,5.064025e+07,0.001581,0.001373
std,14.708247,14.892642,14.526521,14.709644,3.475946e+07,0.019592,0.051749
min,0.121968,0.121968,0.120516,0.120516,0.000000e+00,0.000000,0.000000
25%,0.810214,0.827638,0.797147,0.814571,2.744880e+07,0.000000,0.000000
50%,12.757638,12.917269,12.590077,12.742243,4.456490e+07,0.000000,0.000000
75%,22.624974,22.879999,22.350709,22.617407,6.459720e+07,0.000000,0.000000
max,62.028760,62.292520,60.600833,62.083344,5.677088e+08,0.365000,2.000000

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11289 entries, 0 to 11288
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          11289 non-null  object
 1   Open          11289 non-null  float64
 2   High          11289 non-null  float64
 3   Low           11289 non-null  float64
 4   Close         11289 non-null  float64
 5   Volume        11289 non-null  int64
 6   Dividends     11289 non-null  float64
 7   Stock Splits  11289 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 705.7+ KB

In [6]:
null_val = train.isnull().sum()
null_val

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

In [7]:
nan_val = train.isna().sum()
nan_val

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

In [8]:
train['Date'] = pd.to_datetime(train['Date'])

train.set_index('Date', inplace=True)

train.head()

<ipython-input-8-ca2f29fda85d>:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  train['Date'] = pd.to_datetime(train['Date'])

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-03-17 00:00:00-05:00,0.181500,0.184404,0.181500,0.181500,10924800,0.0,0.0
1980-03-18 00:00:00-05:00,0.181500,0.182952,0.180048,0.180048,17068800,0.0,0.0
1980-03-19 00:00:00-05:00,0.184404,0.187308,0.184404,0.184404,18508800,0.0,0.0
1980-03-20 00:00:00-05:00,0.184403,0.186581,0.183678,0.183678,11174400,0.0,0.0
1980-03-21 00:00:00-05:00,0.180048,0.180048,0.177143,0.177143,12172800,0.0,0.0

In [9]:
train['Daily Return'] = train['Close'].pct_change() * 100

train['7-Day MA'] = train['Close'].rolling(window=7).mean()
train['30-Day MA'] = train['Close'].rolling(window=30).mean()

train.head(10)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily Return,7-Day MA,30-Day MA
Date,,,,,,,,,,
1980-03-17 00:00:00-05:00,0.181500,0.184404,0.181500,0.181500,10924800,0.0,0.0,NaN,NaN,NaN
1980-03-18 00:00:00-05:00,0.181500,0.182952,0.180048,0.180048,17068800,0.0,0.0,-0.799935,NaN,NaN
1980-03-19 00:00:00-05:00,0.184404,0.187308,0.184404,0.184404,18508800,0.0,0.0,2.419199,NaN,NaN
1980-03-20 00:00:00-05:00,0.184403,0.186581,0.183678,0.183678,11174400,0.0,0.0,-0.393694,NaN,NaN
1980-03-21 00:00:00-05:00,0.180048,0.180048,0.177143,0.177143,12172800,0.0,0.0,-3.557432,NaN,NaN
1980-03-24 00:00:00-05:00,0.176417,0.176417,0.173514,0.173514,8966400,0.0,0.0,-2.049001,NaN,NaN
1980-03-25 00:00:00-05:00,0.174240,0.177144,0.174240,0.174240,11347200,0.0,0.0,0.418462,0.179218,NaN
1980-03-26 00:00:00-05:00,0.174240,0.175692,0.172788,0.172788,16262400,0.0,0.0,-0.833300,0.177973,NaN
1980-03-27 00:00:00-05:00,0.169884,0.169884,0.166980,0.166980,26918400,0.0,0.0,-3.361440,0.176106,NaN
1980-03-28 00:00:00-05:00,0.173514,0.176417,0.173514,0.173514,20102400,0.0,0.0,3.913058,0.174551,NaN

In [10]:
train['7-Day MA'] = train['7-Day MA'].fillna(method='ffill').fillna(method='bfill')
train['30-Day MA'] = train['30-Day MA'].fillna(method='ffill').fillna(method='bfill')

train['Daily Return'] = train['Daily Return'].fillna(0)

missing_values_after = train.isnull().sum()
missing_values_after

<ipython-input-10-0ac71e9161bc>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  train['7-Day MA'] = train['7-Day MA'].fillna(method='ffill').fillna(method='bfill')
<ipython-input-10-0ac71e9161bc>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  train['30-Day MA'] = train['30-Day MA'].fillna(method='ffill').fillna(method='bfill')

Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
Daily Return    0
7-Day MA        0
30-Day MA       0
dtype: int64